"use client";

import { useEffect } from "react";

/**
 * Registers the production service worker for the ops workspace. Mounted once
 * in the workspace layout so the SW is only active for users in /ops.
 *
 * The SW itself lives at /sw.js (generated by Serwist at build time). In
 * development the registration is a no-op because next.config.ts disables
 * Serwist outside of production.
 */
export function OpsServiceWorker() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (process.env.NODE_ENV !== "production") return;
    if (!("serviceWorker" in navigator)) return;

    navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .catch(() => {
        // Swallow — registration errors aren't fatal; realtime still falls
        // through to the visibility-based refresher.
      });
  }, []);

  return null;
}
