import { readFile } from "node:fs/promises";
import path from "node:path";
import ExcelJS from "exceljs";
import type { OpsAttendanceRecord } from "@/lib/ops/attendance";

/**
 * Branded attendance register export (audit finding A6).
 *
 * Mirrors the staff payroll register so the two documents read as one family:
 * logo block, title band, summary cards, frozen header, totals row.
 */

const NAVY = "17365D";
const BLUE = "1F4E78";
const PALE_BLUE = "D9EAF7";
const PALE_GREEN = "E2F0D9";
const PALE_YELLOW = "FFF2CC";
const PALE_GREY = "F3F6F9";
const WHITE = "FFFFFF";
const CURRENCY_FORMAT = "[$ZMW] #,##0.00";
const HOURS_FORMAT = "#,##0.00";
const HEADER_ROW = 8;

const COLUMNS = [
  ["Work date", 14],
  ["Worker no.", 14],
  ["Worker name", 26],
  ["Site", 26],
  ["Presence", 12],
  ["Clock in", 11],
  ["Clock out", 11],
  ["Hours worked", 14],
  ["Overtime hours", 15],
  ["Overtime pay", 15],
  ["Earned", 15],
  ["Approval", 14],
  ["Site note", 30],
] as const;

/** Last column letter, derived so adding a column cannot desync the merges. */
const LAST_COLUMN = String.fromCharCode("A".charCodeAt(0) + COLUMNS.length - 1);

export type AttendanceExportMeta = {
  /** Human-readable description of the filters applied, e.g. "All sites | 2026-07-01 to 2026-07-26". */
  scopeLabel: string;
  generatedBy: string;
};

const money = (value: number) => Math.round(value * 100) / 100;

function styleCell(cell: ExcelJS.Cell, options: Partial<ExcelJS.Style>) {
  cell.style = { ...cell.style, ...options };
}

const LUSAKA_DATE = new Intl.DateTimeFormat("en-CA", {
  day: "2-digit",
  month: "2-digit",
  timeZone: "Africa/Lusaka",
  year: "numeric",
});

const LUSAKA_TIME = new Intl.DateTimeFormat("en-GB", {
  hour: "2-digit",
  hour12: false,
  minute: "2-digit",
  timeZone: "Africa/Lusaka",
});

export function attendanceExportFilename(scopeLabel: string) {
  const safeScope = scopeLabel
    .trim()
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `pymble-attendance-register-${safeScope || "all"}.xlsx`;
}

export async function buildAttendanceRegisterXlsx(
  records: OpsAttendanceRecord[],
  meta: AttendanceExportMeta,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Pymble Construction Operations";
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet("Attendance register", {
    pageSetup: {
      fitToHeight: 0,
      fitToPage: true,
      fitToWidth: 1,
      orientation: "landscape",
      paperSize: 9,
    },
    properties: { defaultRowHeight: 18 },
  });
  worksheet.views = [{ showGridLines: false, state: "frozen", ySplit: HEADER_ROW }];
  worksheet.columns = COLUMNS.map(([, width]) => ({ width }));
  worksheet.pageSetup.margins = {
    bottom: 0.4,
    footer: 0.15,
    header: 0.15,
    left: 0.25,
    right: 0.25,
    top: 0.4,
  };

  const logo = (await readFile(path.join(process.cwd(), "public", "logo.png"))).toString("base64");
  const logoId = workbook.addImage({ base64: logo, extension: "png" });
  worksheet.addImage(logoId, "A1:B3");

  worksheet.mergeCells(`C1:${LAST_COLUMN}1`);
  worksheet.mergeCells(`C2:${LAST_COLUMN}2`);
  worksheet.mergeCells(`C3:${LAST_COLUMN}3`);
  worksheet.getCell("C1").value = "PYMBLE CONSTRUCTION";
  worksheet.getCell("C2").value = "ATTENDANCE REGISTER";
  worksheet.getCell("C3").value = `${meta.scopeLabel}  |  Generated by ${meta.generatedBy} on ${LUSAKA_DATE.format(new Date())}`;
  worksheet.getRow(1).height = 26;
  worksheet.getRow(2).height = 24;
  worksheet.getRow(3).height = 22;
  styleCell(worksheet.getCell("C1"), {
    alignment: { vertical: "middle" },
    fill: { fgColor: { argb: NAVY }, pattern: "solid", type: "pattern" },
    font: { bold: true, color: { argb: WHITE }, size: 16 },
  });
  styleCell(worksheet.getCell("C2"), {
    alignment: { vertical: "middle" },
    font: { bold: true, color: { argb: NAVY }, size: 13 },
  });
  styleCell(worksheet.getCell("C3"), {
    alignment: { vertical: "middle" },
    font: { color: { argb: "404040" }, italic: true },
  });

  const totalEarned = money(records.reduce((sum, record) => sum + record.amount_earned, 0));
  const totalOvertimePay = money(records.reduce((sum, record) => sum + record.overtime_amount, 0));
  const totalOvertimeHours = money(records.reduce((sum, record) => sum + record.overtime_hours, 0));
  const totalHours = money(records.reduce((sum, record) => sum + record.hours_worked, 0));
  const pendingCount = records.filter((record) => !record.approved_at).length;

  const cards: Array<[string, string, string, number, string, string]> = [
    ["A5:B5", "A6:B6", "Records", records.length, PALE_BLUE, HOURS_FORMAT],
    ["C5:D5", "C6:D6", "Pending approval", pendingCount, PALE_YELLOW, HOURS_FORMAT],
    ["E5:F5", "E6:F6", "Hours worked", totalHours, PALE_GREY, HOURS_FORMAT],
    ["G5:H5", "G6:H6", "Overtime hours", totalOvertimeHours, PALE_GREY, HOURS_FORMAT],
    ["I5:J5", "I6:J6", "Overtime pay", totalOvertimePay, PALE_YELLOW, CURRENCY_FORMAT],
    ["K5:L5", "K6:L6", "Total earned", totalEarned, PALE_GREEN, CURRENCY_FORMAT],
  ];

  for (const [labelRange, valueRange, label, value, fill, format] of cards) {
    worksheet.mergeCells(labelRange);
    worksheet.mergeCells(valueRange);
    const labelCell = worksheet.getCell(labelRange.split(":")[0]);
    const valueCell = worksheet.getCell(valueRange.split(":")[0]);
    labelCell.value = label;
    valueCell.value = value;
    valueCell.numFmt = format;
    styleCell(labelCell, {
      alignment: { horizontal: "center", vertical: "middle" },
      fill: { fgColor: { argb: fill }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY }, size: 9 },
    });
    styleCell(valueCell, {
      alignment: { horizontal: "center", vertical: "middle" },
      fill: { fgColor: { argb: fill }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY }, size: 12 },
    });
  }

  const headerRow = worksheet.getRow(HEADER_ROW);
  headerRow.values = COLUMNS.map(([label]) => label);
  headerRow.height = 24;
  headerRow.eachCell((cell) => {
    styleCell(cell, {
      alignment: { horizontal: "center", vertical: "middle", wrapText: true },
      fill: { fgColor: { argb: BLUE }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: WHITE }, size: 10 },
    });
  });

  records.forEach((record, index) => {
    const row = worksheet.getRow(HEADER_ROW + 1 + index);
    row.values = [
      LUSAKA_DATE.format(new Date(record.clock_in_at)),
      record.worker?.worker_code ?? "",
      record.worker?.full_name ?? "",
      record.site?.code ? `${record.site.code} - ${record.site.name}` : "",
      record.presence,
      LUSAKA_TIME.format(new Date(record.clock_in_at)),
      record.clock_out_at ? LUSAKA_TIME.format(new Date(record.clock_out_at)) : "",
      record.hours_worked,
      record.overtime_hours,
      record.overtime_amount,
      record.amount_earned,
      record.approved_at ? "Approved" : "Pending",
      record.site_note,
    ];

    row.getCell(5).alignment = { horizontal: "center" };
    row.getCell(8).numFmt = HOURS_FORMAT;
    row.getCell(9).numFmt = HOURS_FORMAT;
    row.getCell(10).numFmt = CURRENCY_FORMAT;
    row.getCell(11).numFmt = CURRENCY_FORMAT;
    row.getCell(12).alignment = { horizontal: "center" };

    if (index % 2 === 1) {
      row.eachCell((cell) => {
        styleCell(cell, {
          fill: { fgColor: { argb: PALE_GREY }, pattern: "solid", type: "pattern" },
        });
      });
    }

    if (!record.approved_at) {
      styleCell(row.getCell(12), { font: { bold: true, color: { argb: "9C5700" } } });
    }
  });

  const totalsRow = worksheet.getRow(HEADER_ROW + 1 + records.length);
  totalsRow.values = [
    "TOTAL",
    "",
    `${records.length} record${records.length === 1 ? "" : "s"}`,
    "",
    "",
    "",
    "",
    totalHours,
    totalOvertimeHours,
    totalOvertimePay,
    totalEarned,
    `${pendingCount} pending`,
    "",
  ];
  totalsRow.getCell(8).numFmt = HOURS_FORMAT;
  totalsRow.getCell(9).numFmt = HOURS_FORMAT;
  totalsRow.getCell(10).numFmt = CURRENCY_FORMAT;
  totalsRow.getCell(11).numFmt = CURRENCY_FORMAT;
  totalsRow.eachCell((cell) => {
    styleCell(cell, {
      border: { top: { color: { argb: NAVY }, style: "medium" } },
      fill: { fgColor: { argb: PALE_BLUE }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY } },
    });
  });

  worksheet.autoFilter = {
    from: { column: 1, row: HEADER_ROW },
    to: { column: COLUMNS.length, row: HEADER_ROW + records.length },
  };

  return Buffer.from(await workbook.xlsx.writeBuffer());
}
