import { COMPANY, CONTACT } from "@/lib/constants";
import type { OpsModule, OpsModuleGroup, OpsUserRole } from "@/lib/ops/types";

export const OPS_HOST = "ops.pymbleconstruction.com";

export const OPS_BRAND = {
  name: "Pymble Operations",
  companyName: COMPANY.legalName,
  shortName: "Pymble Ops",
  supportEmail: CONTACT.email,
  supportPhone: CONTACT.phone.primary,
} as const;

const OPS_OPERATIONAL_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "human_resource",
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "hse_officer",
  "hse_assistant_officer",
  "admin_receptionist",
  "owner",
  "hr",
  "manager",
  "supervisor",
];

const OPS_LEADERSHIP_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "owner",
];

const OPS_EXECUTIVE_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "manager",
];

const OPS_SITE_DELIVERY_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "engineer",
  "hse_officer",
  "hse_assistant_officer",
  "manager",
  "supervisor",
];

const OPS_PROCUREMENT_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "procurement_manager",
  "procurement",
  "procurement_assistant",
];

const OPS_MATERIAL_REQUEST_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "engineer",
  "manager",
  "supervisor",
];

const OPS_SUPPLIER_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "manager",
];

const OPS_RFQ_PO_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "manager",
];

const OPS_STORES_INVENTORY_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "manager",
  "supervisor",
];

const OPS_DELIVERY_EXCEPTION_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "manager",
  "supervisor",
];

const OPS_DAILY_SITE_REPORT_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "finance_manager",
  "accountant",
  "engineer",
  "hse_officer",
  "hse_assistant_officer",
  "manager",
  "supervisor",
];

const OPS_ENGINEERING_CONTROL_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  "quantity_surveyor",
];

const OPS_FINANCE_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "finance_manager",
  "accountant",
];

const OPS_FINANCE_BRIDGE_ROLES: OpsUserRole[] = [
  ...OPS_FINANCE_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "manager",
];

const OPS_EQUIPMENT_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  ...OPS_FINANCE_ROLES,
  "procurement_manager",
  "procurement",
  "quantity_surveyor",
];

const OPS_COMMERCIAL_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "projects_manager",
  "quantity_surveyor",
  "finance_manager",
  "accountant",
  "engineer",
];

const OPS_HSE_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  "hse_officer",
  "hse_assistant_officer",
];

const OPS_HR_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "human_resource",
  "hr",
  "admin_receptionist",
];

const OPS_FLEET_LOGISTICS_ROLES: OpsUserRole[] = [
  ...OPS_EQUIPMENT_ROLES,
  ...OPS_HR_ROLES,
  "admin_receptionist",
];

const OPS_DOCUMENT_ROLES: OpsUserRole[] = [
  ...OPS_OPERATIONAL_ROLES,
  "human_resource",
];

const OPS_STAFF_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "human_resource",
  "owner",
  "hr",
  "manager",
];

export const OPS_MODULE_GROUPS: OpsModuleGroup[] = [
  {
    id: "operations",
    title: "Operations",
    description: "Run day-to-day site work, approvals, attendance, payroll, and field requests.",
  },
  {
    id: "commercial",
    title: "Commercial",
    description: "Manage project value from BOQ through invoices, claims, variations, and contracts.",
  },
  {
    id: "records",
    title: "Records",
    description: "Keep company records, documents, staff access, photos, and settings organized.",
  },
  {
    id: "engineering",
    title: "Engineering",
    description: "Control instructions, Quality Assurance and Quality Control, progress records, tests, snags, and drawings.",
  },
  {
    id: "procurement",
    title: "Procurement and Stores",
    description: "Move materials from supplier selection through purchasing, delivery, and stock control.",
  },
  {
    id: "finance",
    title: "Finance and Accounts",
    description: "Track budgets, payment requests, supplier ageing, cashflow, and project costs.",
  },
  {
    id: "fleet",
    title: "Operations and Fleet",
    description: "Coordinate equipment, fuel, maintenance, transport, accommodation, and site logistics.",
  },
  {
    id: "hse",
    title: "Health, Safety and Environment",
    description: "Record incidents, Personal Protective Equipment, toolbox talks, inspections, training, and corrective actions.",
  },
  {
    id: "hr",
    title: "Administration and Human Resources",
    description: "Manage employee records, recruitment, leave, contracts, appraisals, and Human Resources documents.",
  },
  {
    id: "executive",
    title: "Executive",
    description: "Review approvals, project risk, cashflow, margins, safety, and delivery health.",
  },
];

export const OPS_MODULES: OpsModule[] = [
  {
    description: "See today's priorities, live project signals, map activity, and workflow pressure in one place.",
    group: "operations",
    href: "/ops",
    id: "overview",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Overview",
  },
  {
    description: "Create and maintain site records with budgets, supervisors, clients, locations, and map coordinates.",
    group: "operations",
    href: "/ops/sites",
    id: "sites",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Projects and Sites",
  },
  {
    description: "Keep crew records ready for site assignment, attendance, payroll, and contact follow-up.",
    group: "operations",
    href: "/ops/workers",
    id: "workers",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Workers",
  },
  {
    description: "Record attendance, review timesheets, and keep payroll-ready site labour history.",
    group: "operations",
    href: "/ops/attendance",
    id: "attendance",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Attendance",
  },
  {
    description: "Review submitted records, capture decisions, and keep approval history traceable.",
    group: "operations",
    href: "/ops/approvals",
    id: "approvals",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Approvals",
  },
  {
    description: "Track the alerts and workflow messages that need your attention.",
    group: "operations",
    href: "/ops/notifications",
    id: "notifications",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Notifications",
  },
  {
    description: "Every comment where a teammate @mentioned you — reply on the record.",
    group: "operations",
    href: "/ops/inbox",
    id: "inbox",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "My Conversations",
  },
  {
    description: "Manage advances, approved payroll runs, and payout progress for site labour.",
    group: "operations",
    href: "/ops/payroll",
    id: "payroll",
    navigationRoles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Foundation",
    // Sprint 8: payroll is HR + Finance + Leadership only. Previously this
    // used OPS_OPERATIONAL_ROLES which let Procurement / HSE / Engineering
    // see payroll — a data leak across the organogram.
    roles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    status: "ready",
    title: "Payroll",
  },
  {
    description: "Build project Bills of Quantities, track line items, compare quantities, and prepare exportable records.",
    group: "commercial",
    href: "/ops/boq",
    id: "boq",
    navigationRoles: [...OPS_COMMERCIAL_ROLES, ...OPS_PROCUREMENT_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Bill of Quantities",
  },
  {
    description: "Create client invoices, apply Value Added Tax details, track status, and prepare PDF outputs.",
    group: "commercial",
    href: "/ops/invoices",
    id: "invoices",
    navigationRoles: [...OPS_FINANCE_ROLES, "quantity_surveyor"],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Invoices",
  },
  {
    description: "Secure site photo logs for progress, deliveries, and safety records.",
    group: "records",
    href: "/ops/photos",
    id: "photos",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HSE_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Photos",
  },
  {
    description: "Upload, version, and review internal documents with controlled access.",
    group: "records",
    href: "/ops/documents",
    id: "documents",
    navigationRoles: OPS_DOCUMENT_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Documents",
  },
  {
    description: "View the modules available to your role and the roadmap for upcoming work areas.",
    group: "records",
    href: "/ops/modules",
    id: "modules",
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    showInNavigation: false,
    status: "ready",
    title: "Modules",
  },
  {
    description: "Look up the full meaning of every abbreviation used in the operations workspace in plain English.",
    group: "records",
    href: "/ops/glossary",
    id: "glossary",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Glossary",
  },
  {
    description: "Create invite-only Pymble staff accounts and manage internal access roles.",
    group: "records",
    href: "/ops/staff",
    id: "staff",
    navigationRoles: OPS_STAFF_ROLES,
    phase: "Foundation",
    roles: OPS_STAFF_ROLES,
    status: "ready",
    title: "Staff",
  },
  {
    description: "Maintain company details, headquarters coordinates, invoice defaults, and approval thresholds.",
    group: "records",
    href: "/ops/settings",
    id: "settings",
    navigationRoles: OPS_LEADERSHIP_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Settings",
  },
  {
    description: "Capture daily site progress, labour, equipment, materials, delays, and productivity notes.",
    group: "engineering",
    href: "/ops/daily-site-reports",
    id: "daily-site-reports",
    navigationRoles: OPS_DAILY_SITE_REPORT_ROLES,
    phase: "Phase 2",
    roles: OPS_DAILY_SITE_REPORT_ROLES,
    status: "ready",
    title: "Daily Site Reports",
  },
  {
    description: "Raise site material needs, add line items, and move approved requests into procurement.",
    group: "operations",
    href: "/ops/material-requests",
    id: "material-requests",
    navigationRoles: OPS_MATERIAL_REQUEST_ROLES,
    phase: "Phase 2",
    roles: OPS_MATERIAL_REQUEST_ROLES,
    status: "ready",
    title: "Material Requests",
  },
  {
    description: "Issue site instructions, inspect work, track tests, close snags, and manage drawings.",
    group: "engineering",
    href: "/ops/engineering-controls",
    id: "engineering-controls",
    navigationRoles: OPS_ENGINEERING_CONTROL_ROLES,
    phase: "Phase 2",
    roles: OPS_ENGINEERING_CONTROL_ROLES,
    status: "ready",
    title: "Site Instructions and Quality Assurance / Quality Control",
  },
  {
    description: "Maintain supplier profiles, contacts, compliance status, and performance evidence.",
    group: "records",
    href: "/ops/suppliers",
    id: "suppliers",
    navigationRoles: OPS_SUPPLIER_ROLES,
    phase: "Phase 2",
    roles: OPS_SUPPLIER_ROLES,
    status: "ready",
    title: "Suppliers",
  },
  {
    description: "Prepare Requests for Quotation, compare supplier quotes, award orders, and manage Purchase Order approvals.",
    group: "operations",
    href: "/ops/rfq-po",
    id: "rfq-po",
    navigationRoles: OPS_RFQ_PO_ROLES,
    phase: "Phase 2",
    roles: OPS_RFQ_PO_ROLES,
    status: "ready",
    title: "Requests for Quotation and Purchase Orders",
  },
  {
    description: "Post deliveries, monitor store balances, and record stock issues, transfers, and adjustments.",
    group: "operations",
    href: "/ops/stores-inventory",
    id: "stores-inventory",
    navigationRoles: OPS_STORES_INVENTORY_ROLES,
    phase: "Phase 2",
    roles: OPS_STORES_INVENTORY_ROLES,
    status: "ready",
    title: "Stores and Inventory",
  },
  {
    description: "Log delivery problems, assign follow-up, and close shortages or damage with evidence.",
    group: "operations",
    href: "/ops/delivery-exceptions",
    id: "delivery-exceptions",
    navigationRoles: OPS_DELIVERY_EXCEPTION_ROLES,
    phase: "Phase 2",
    roles: OPS_DELIVERY_EXCEPTION_ROLES,
    status: "ready",
    title: "Delivery Exceptions",
  },
  {
    description: "Set project budgets, track cost lines, approve revisions, and watch budget variance.",
    group: "finance",
    href: "/ops/project-budgets",
    id: "project-budgets",
    navigationRoles: [...OPS_FINANCE_ROLES, "projects_manager", "quantity_surveyor"],
    phase: "Phase 3",
    roles: OPS_FINANCE_BRIDGE_ROLES,
    status: "ready",
    title: "Project Budgets",
  },
  {
    description: "Submit payment requests, review supplier ageing, and track cashflow impact.",
    group: "finance",
    href: "/ops/payment-requests",
    id: "payment-requests",
    navigationRoles: OPS_FINANCE_BRIDGE_ROLES,
    phase: "Phase 3",
    roles: OPS_FINANCE_BRIDGE_ROLES,
    status: "ready",
    title: "Payment Requests",
  },
  {
    description: "Manage equipment, site requests, allocations, utilization, and related project costs.",
    group: "fleet",
    href: "/ops/equipment",
    id: "equipment",
    navigationRoles: OPS_EQUIPMENT_ROLES,
    phase: "Phase 4",
    roles: OPS_EQUIPMENT_ROLES,
    status: "ready",
    title: "Equipment",
  },
  {
    description: "Plan transport, accommodation, labour movement, dispatch calendars, and logistics costs.",
    group: "fleet",
    href: "/ops/fleet-logistics",
    id: "fleet-logistics",
    navigationRoles: OPS_FLEET_LOGISTICS_ROLES,
    phase: "Phase 4",
    roles: OPS_FLEET_LOGISTICS_ROLES,
    status: "ready",
    title: "Fleet and Logistics",
  },
  {
    description: "Report incidents and near misses, investigate causes, and close corrective actions.",
    group: "hse",
    href: "/ops/hse",
    id: "hse-incidents",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Incidents and Actions",
  },
  {
    description: "Manage Personal Protective Equipment, toolbox talks, training, inspections, risk assessments, and audit actions.",
    group: "hse",
    href: "/ops/hse-compliance",
    id: "hse-compliance",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Health, Safety and Environment Compliance",
  },
  {
    description: "Roll up the week's safety picture (incidents, near misses, Personal Protective Equipment compliance, toolbox talks) and surface it to leadership.",
    group: "hse",
    href: "/ops/hse-weekly",
    id: "hse-weekly",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Weekly Health, Safety and Environment Report",
  },
  {
    description: "Manage employee files, leave, recruitment, contracts, appraisals, and Human Resources documents.",
    group: "hr",
    href: "/ops/employees",
    id: "employees",
    phase: "Phase 5",
    navigationRoles: OPS_HR_ROLES,
    roles: OPS_HR_ROLES,
    status: "ready",
    title: "Employees and Leave",
  },
  {
    description: "Publish job openings to the website, review candidate applications, and move applicants through hiring stages.",
    group: "hr",
    href: "/ops/recruitment",
    id: "recruitment",
    phase: "Phase 5",
    navigationRoles: OPS_HR_ROLES,
    roles: OPS_HR_ROLES,
    status: "ready",
    title: "Recruitment",
  },
  {
    description: "Track Interim Payment Certificates, valuations, variations, claims, contract milestones, and commercial risk.",
    group: "commercial",
    href: "/ops/commercial",
    id: "commercial-maturity",
    navigationRoles: OPS_COMMERCIAL_ROLES,
    phase: "Phase 6",
    roles: OPS_COMMERCIAL_ROLES,
    status: "ready",
    title: "Interim Payment Certificates, Variations and Claims",
  },
  {
    description: "Monitor executive action queues, cashflow, project delay, profitability, safety, and risk.",
    group: "executive",
    href: "/ops/executive",
    id: "executive-dashboard",
    navigationRoles: OPS_EXECUTIVE_ROLES,
    phase: "Phase 7",
    roles: OPS_EXECUTIVE_ROLES,
    status: "ready",
    title: "Executive Dashboard",
  },
];
