import { COMPANY, CONTACT } from "@/lib/constants";
import type { OpsModule, OpsModuleGroup, OpsUserRole } from "@/lib/ops/types";

export const OPS_HOST = "ops.pymbleconstruction.com";

export const OPS_BRAND = {
  name: "Pymble Operations",
  companyName: COMPANY.legalName,
  shortName: "Pymble Ops",
  supportEmail: CONTACT.email,
  supportPhone: CONTACT.phone.primary,
} as const;

const OPS_OPERATIONAL_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "human_resource",
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "hse_officer",
  "hse_assistant_officer",
  "admin_receptionist",
  "owner",
  "hr",
  "manager",
  "supervisor",
];

const OPS_LEADERSHIP_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "owner",
];

const OPS_EXECUTIVE_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "manager",
];

// Back-office oversight tools (Activity Log, Archive): leadership + manager +
// Operations Manager. Mirrors canViewOpsBackoffice in permissions.ts.
const OPS_BACKOFFICE_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "manager",
  "operations_manager",
];

const OPS_SITE_DELIVERY_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "engineer",
  "hse_officer",
  "hse_assistant_officer",
  "manager",
  "supervisor",
];

const OPS_PROCUREMENT_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "procurement_manager",
  "procurement",
  "procurement_assistant",
];

const OPS_MATERIAL_REQUEST_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  // Finance must open the priced queue to make the shared cost decision.
  "finance_manager",
  "accountant",
  "engineer",
  "manager",
  "supervisor",
  // HSE raise PPE / safety-equipment requisitions through the same flow, so the
  // nav entry + page access must match canCreateOpsMaterialRequest, which
  // already allows these roles.
  "hse_officer",
  "hse_assistant_officer",
  // IT raises confidential IT-scoped requests through the same module.
  "it_manager",
];

const OPS_SUPPLIER_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "manager",
];

const OPS_RFQ_PO_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "manager",
];

const OPS_STORES_INVENTORY_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "manager",
  "supervisor",
];

const OPS_DELIVERY_EXCEPTION_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "procurement_assistant",
  "finance_manager",
  "accountant",
  "engineer",
  "manager",
  "supervisor",
];

const OPS_DAILY_SITE_REPORT_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "operations_manager",
  "projects_manager",
  "engineering_manager",
  "procurement_manager",
  "quantity_surveyor",
  "finance_manager",
  "accountant",
  "engineer",
  "engineering_intern",
  "hse_officer",
  "hse_assistant_officer",
  "manager",
  "supervisor",
];

const OPS_ENGINEERING_CONTROL_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  "quantity_surveyor",
];

const OPS_FINANCE_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "finance_manager",
  "accountant",
];

const OPS_FINANCE_BRIDGE_ROLES: OpsUserRole[] = [
  ...OPS_FINANCE_ROLES,
  "operations_manager",
  "projects_manager",
  "procurement_manager",
  "quantity_surveyor",
  "procurement",
  "manager",
];

const OPS_EQUIPMENT_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  ...OPS_FINANCE_ROLES,
  "procurement_manager",
  "procurement",
  "quantity_surveyor",
];

const OPS_COMMERCIAL_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "projects_manager",
  "quantity_surveyor",
  "finance_manager",
  "accountant",
  "engineer",
];

// Leadership + accounts + HR + procurement. Mirrors
// `canViewOpsQuotations` in src/lib/ops/quotation-permissions.ts — note it
// excludes admin_receptionist, so it is not OPS_HR_ROLES.
const OPS_QUOTATION_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "finance_manager",
  "accountant",
  "human_resource",
  "hr",
  "procurement_manager",
  "procurement",
  "procurement_assistant",
];

const OPS_HSE_ROLES: OpsUserRole[] = [
  ...OPS_SITE_DELIVERY_ROLES,
  "hse_officer",
  "hse_assistant_officer",
];

const OPS_HR_ROLES: OpsUserRole[] = [
  ...OPS_LEADERSHIP_ROLES,
  "human_resource",
  "hr",
  "admin_receptionist",
];

const OPS_FLEET_LOGISTICS_ROLES: OpsUserRole[] = [
  ...OPS_EQUIPMENT_ROLES,
  ...OPS_HR_ROLES,
  "admin_receptionist",
];

const OPS_DOCUMENT_ROLES: OpsUserRole[] = [
  ...OPS_OPERATIONAL_ROLES,
  "human_resource",
];

const OPS_STAFF_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "general_manager",
  "human_resource",
  "owner",
  "hr",
  "manager",
];

/**
 * Information Technology is a role-isolated area. Only the IT Manager runs it;
 * the Managing Director / Owner keep oversight, and the Developer retains
 * maintenance access (mirrors how leadership sits above every other module).
 * The General Manager is intentionally excluded — IT reports to the MD.
 */
const OPS_IT_ROLES: OpsUserRole[] = [
  "developer",
  "managing_director",
  "owner",
  "it_manager",
];

/**
 * Nav buckets ordered from doing the work → tracking it → oversight, so the
 * sidebar reads as a delivery flow rather than an alphabetical pile. The `id`
 * of each group is stable (used in module assignments + permission paths) —
 * only `title` / `description` / order may change.
 */
export const OPS_MODULE_GROUPS: OpsModuleGroup[] = [
  {
    id: "operations",
    title: "Operations",
    description: "Run day-to-day site work, attendance, approvals, and field coordination.",
  },
  {
    id: "engineering",
    title: "Engineering",
    description: "Control instructions, Quality Assurance and Quality Control, progress records, tests, snags, and drawings.",
  },
  {
    id: "procurement",
    title: "Procurement and Stores",
    description: "Material requests, supplier records, requisitions, purchase orders, deliveries, and stock control.",
  },
  {
    id: "fleet",
    title: "Fleet and Equipment",
    description: "Coordinate equipment, fuel, maintenance, transport, accommodation, and site logistics.",
  },
  {
    id: "commercial",
    title: "Commercial",
    description: "Manage project value from BOQ through invoices, claims, variations, and contracts.",
  },
  {
    id: "finance",
    title: "Finance and Accounts",
    description: "Track budgets, payment requests, supplier ageing, cashflow, and project costs.",
  },
  {
    id: "hr",
    title: "Human Resources",
    description: "Manage employee records, contracts, payroll, recruitment, leave, appraisals, and HR documents.",
  },
  {
    id: "hse",
    title: "Health, Safety and Environment",
    description: "Record incidents, Personal Protective Equipment, toolbox talks, inspections, training, and corrective actions.",
  },
  {
    id: "records",
    title: "Records",
    description: "Cross-cutting tools — documents, photos, glossary, activity log, archive, and settings.",
  },
  {
    id: "it",
    title: "Information Technology",
    description: "Manage IT assets, the internal help desk, software, access, and IT policies. Restricted to IT and the Managing Director.",
  },
  {
    id: "executive",
    title: "Executive",
    description: "Review approvals, project risk, cashflow, margins, safety, and delivery health.",
  },
];

export const OPS_MODULES: OpsModule[] = [
  {
    description: "See today's priorities, live project signals, map activity, and workflow pressure in one place.",
    group: "operations",
    href: "/ops",
    id: "overview",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Overview",
  },
  {
    description: "Create and maintain site records with budgets, supervisors, clients, locations, and map coordinates.",
    group: "operations",
    href: "/ops/sites",
    id: "sites",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Projects and Sites",
  },
  {
    description: "Your assigned construction sites, attendance capture, daily reporting, and field-support shortcuts.",
    group: "operations",
    href: "/ops/my-sites",
    id: "my-sites",
    navigationRoles: ["engineering_intern"],
    phase: "Intern workflow",
    roles: [...OPS_LEADERSHIP_ROLES, "engineering_intern"],
    status: "ready",
    title: "My Sites",
  },
  {
    description: "Keep crew records ready for site assignment, attendance, payroll, and contact follow-up.",
    group: "operations",
    href: "/ops/workers",
    id: "workers",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Workers",
  },
  {
    description: "Record attendance, review timesheets, and keep payroll-ready site labour history.",
    group: "operations",
    href: "/ops/attendance",
    id: "attendance",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES, "engineering_intern"],
    phase: "Foundation",
    roles: [...OPS_OPERATIONAL_ROLES, "engineering_intern"],
    status: "ready",
    title: "Attendance",
  },
  {
    description: "Review submitted records, capture decisions, and keep approval history traceable.",
    group: "operations",
    href: "/ops/approvals",
    id: "approvals",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Approvals",
  },
  {
    description: "Track the alerts and workflow messages that need your attention.",
    group: "operations",
    href: "/ops/notifications",
    id: "notifications",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Notifications",
  },
  {
    description: "Every comment where a teammate @mentioned you — reply on the record.",
    group: "operations",
    href: "/ops/inbox",
    id: "inbox",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "My Conversations",
  },
  {
    description: "Manage advances, approved payroll runs, and payout progress for site labour.",
    group: "hr",
    href: "/ops/payroll",
    id: "payroll",
    navigationRoles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Foundation",
    // Sprint 8: payroll is HR + Finance + Leadership only. Previously this
    // used OPS_OPERATIONAL_ROLES which let Procurement / HSE / Engineering
    // see payroll — a data leak across the organogram.
    roles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    status: "ready",
    title: "Payroll",
  },
  {
    description: "Generate monthly staff payslips (basic + housing + allowances, with PAYE / NAPSA / NHIMA). Employees self-download from their profile.",
    group: "hr",
    href: "/ops/staff-payroll",
    id: "staff-payroll",
    navigationRoles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    phase: "Phase 8",
    roles: [...OPS_LEADERSHIP_ROLES, ...OPS_HR_ROLES, ...OPS_FINANCE_ROLES],
    status: "ready",
    title: "Staff Payroll",
  },
  {
    description: "Build the project material schedule: measured lines, procurement pricing, revisions, and the project budget generated from it.",
    group: "commercial",
    href: "/ops/material-schedule",
    id: "boq",
    navigationRoles: [...OPS_COMMERCIAL_ROLES, ...OPS_PROCUREMENT_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Material Schedule",
  },
  {
    description: "Prepare priced client quotations with VAT, track whether they were accepted, and export a branded PDF.",
    group: "commercial",
    href: "/ops/quotations",
    id: "quotations",
    navigationRoles: OPS_QUOTATION_ROLES,
    phase: "Foundation",
    roles: OPS_QUOTATION_ROLES,
    status: "ready",
    title: "Quotations",
  },
  {
    description: "Create client invoices, apply Value Added Tax details, track status, and prepare PDF outputs.",
    group: "commercial",
    href: "/ops/invoices",
    id: "invoices",
    navigationRoles: [...OPS_FINANCE_ROLES, "quantity_surveyor"],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Invoices",
  },
  {
    description: "The customer master behind client invoices — legal identity, TPIN, and contact details.",
    group: "commercial",
    href: "/ops/customers",
    id: "customers",
    navigationRoles: [...OPS_LEADERSHIP_ROLES, "manager", "finance_manager", "accountant", "quantity_surveyor"],
    phase: "Phase 13",
    roles: [...OPS_LEADERSHIP_ROLES, "manager", "finance_manager", "accountant", "quantity_surveyor"],
    status: "ready",
    title: "Customers",
  },
  {
    description: "Secure site photo logs for progress, deliveries, and safety records.",
    group: "records",
    href: "/ops/photos",
    id: "photos",
    navigationRoles: [...OPS_SITE_DELIVERY_ROLES, ...OPS_HSE_ROLES],
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Photos",
  },
  {
    description: "Upload, version, and review internal documents with controlled access.",
    group: "records",
    href: "/ops/documents",
    id: "documents",
    navigationRoles: OPS_DOCUMENT_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Documents",
  },
  {
    description: "View the modules available to your role and the roadmap for upcoming work areas.",
    group: "records",
    href: "/ops/modules",
    id: "modules",
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    showInNavigation: false,
    status: "ready",
    title: "Modules",
  },
  {
    description: "Look up the full meaning of every abbreviation used in the operations workspace in plain English.",
    group: "records",
    href: "/ops/glossary",
    id: "glossary",
    navigationRoles: OPS_OPERATIONAL_ROLES,
    phase: "Phase 1",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Glossary",
  },
  {
    description: "Create invite-only Pymble staff accounts and manage internal access roles.",
    group: "hr",
    href: "/ops/staff",
    id: "staff",
    navigationRoles: OPS_STAFF_ROLES,
    phase: "Foundation",
    roles: OPS_STAFF_ROLES,
    status: "ready",
    title: "Staff",
  },
  {
    description: "Every recorded action across the workspace — who did what, when, and in which module. Oversight for leadership and the Operations Manager.",
    group: "records",
    href: "/ops/activity",
    id: "activity-log",
    navigationRoles: OPS_BACKOFFICE_ROLES,
    phase: "Phase 7",
    roles: OPS_BACKOFFICE_ROLES,
    status: "ready",
    title: "Activity Log",
  },
  {
    description: "Archived records across the workspace — workers, sites, suppliers, requests, equipment and more. Leadership and the Operations Manager can restore them.",
    group: "records",
    href: "/ops/archive",
    id: "archive",
    navigationRoles: OPS_BACKOFFICE_ROLES,
    phase: "Phase 7",
    roles: OPS_BACKOFFICE_ROLES,
    status: "ready",
    title: "Archive",
  },
  {
    description: "Maintain company details, headquarters coordinates, invoice defaults, and approval thresholds.",
    group: "records",
    href: "/ops/settings",
    id: "settings",
    navigationRoles: OPS_LEADERSHIP_ROLES,
    phase: "Foundation",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Settings",
  },
  {
    description: "Capture daily site progress, labour, equipment, materials, delays, and productivity notes.",
    group: "engineering",
    href: "/ops/daily-site-reports",
    id: "daily-site-reports",
    navigationRoles: OPS_DAILY_SITE_REPORT_ROLES,
    phase: "Phase 2",
    roles: OPS_DAILY_SITE_REPORT_ROLES,
    status: "ready",
    title: "Daily Site Reports",
  },
  {
    description: "Raise site material needs, add line items, and move approved requests into procurement.",
    group: "procurement",
    href: "/ops/material-requests",
    id: "material-requests",
    navigationRoles: OPS_MATERIAL_REQUEST_ROLES,
    phase: "Phase 2",
    roles: OPS_MATERIAL_REQUEST_ROLES,
    status: "ready",
    title: "Material Requests",
  },
  {
    description: "Issue site instructions, inspect work, track tests, close snags, and manage drawings.",
    group: "engineering",
    href: "/ops/engineering-controls",
    id: "engineering-controls",
    navigationRoles: OPS_ENGINEERING_CONTROL_ROLES,
    phase: "Phase 2",
    roles: OPS_ENGINEERING_CONTROL_ROLES,
    status: "ready",
    title: "Site Instructions and Quality Assurance / Quality Control",
  },
  {
    description: "Per-site task schedule with planned dates and assigned engineers. Engineers mark progress; the system computes site completion and flags overdue tasks.",
    group: "engineering",
    href: "/ops/project-schedule",
    id: "project-schedule",
    navigationRoles: OPS_ENGINEERING_CONTROL_ROLES,
    phase: "Phase 6",
    roles: OPS_ENGINEERING_CONTROL_ROLES,
    status: "ready",
    title: "Project Schedule and Progress",
  },
  {
    description: "Maintain supplier profiles, contacts, compliance status, and performance evidence.",
    group: "procurement",
    href: "/ops/suppliers",
    id: "suppliers",
    navigationRoles: OPS_SUPPLIER_ROLES,
    phase: "Phase 2",
    roles: OPS_SUPPLIER_ROLES,
    status: "ready",
    title: "Suppliers",
  },
  {
    description: "Raise purchasing requisitions, nominate a supplier per line, record actual prices, convert to draft purchase orders, and manage Purchase Order approvals.",
    group: "procurement",
    href: "/ops/rfq-po",
    id: "rfq-po",
    navigationRoles: OPS_RFQ_PO_ROLES,
    phase: "Phase 2",
    roles: OPS_RFQ_PO_ROLES,
    status: "ready",
    title: "Requisitions and Purchase Orders",
  },
  {
    description: "Post deliveries, monitor store balances, and record stock issues, transfers, and adjustments.",
    group: "procurement",
    href: "/ops/stores-inventory",
    id: "stores-inventory",
    navigationRoles: OPS_STORES_INVENTORY_ROLES,
    phase: "Phase 2",
    roles: OPS_STORES_INVENTORY_ROLES,
    status: "ready",
    title: "Stores and Inventory",
  },
  {
    description: "Log delivery problems, assign follow-up, and close shortages or damage with evidence.",
    group: "procurement",
    href: "/ops/delivery-exceptions",
    id: "delivery-exceptions",
    navigationRoles: OPS_DELIVERY_EXCEPTION_ROLES,
    phase: "Phase 2",
    roles: OPS_DELIVERY_EXCEPTION_ROLES,
    status: "ready",
    title: "Delivery Exceptions",
  },
  {
    description: "One view of cashflow, receivables, payables, budget variance, and project margin.",
    group: "finance",
    href: "/ops/finance",
    id: "finance-overview",
    navigationRoles: OPS_FINANCE_BRIDGE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_BRIDGE_ROLES,
    status: "ready",
    title: "Finance Overview",
  },
  {
    description: "Set project budgets, track cost lines, approve revisions, and watch budget variance.",
    group: "finance",
    href: "/ops/project-budgets",
    id: "project-budgets",
    navigationRoles: [...OPS_FINANCE_ROLES, "projects_manager", "quantity_surveyor"],
    phase: "Phase 3",
    roles: OPS_FINANCE_BRIDGE_ROLES,
    status: "ready",
    title: "Project Budgets",
  },
  {
    description: "Submit payment requests, review supplier ageing, and track cashflow impact.",
    group: "finance",
    href: "/ops/payment-requests",
    id: "payment-requests",
    navigationRoles: OPS_FINANCE_BRIDGE_ROLES,
    phase: "Phase 3",
    roles: OPS_FINANCE_BRIDGE_ROLES,
    status: "ready",
    title: "Payment Requests",
  },
  {
    description: "The general ledger chart of accounts — asset, liability, equity, income, and expense accounts.",
    group: "finance",
    href: "/ops/finance/accounts",
    id: "chart-of-accounts",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Chart of Accounts",
  },
  {
    description: "Posted debit and credit totals per account — the proof the ledger balances.",
    group: "finance",
    href: "/ops/finance/trial-balance",
    id: "trial-balance",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Trial Balance",
  },
  {
    description: "The double-entry general ledger journal — every posted, balanced, immutable entry.",
    group: "finance",
    href: "/ops/finance/journal",
    id: "general-ledger-journal",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Journal",
  },
  {
    description: "Revenue, cost of sales, and operating expenses since the ledger went live.",
    group: "finance",
    href: "/ops/finance/profit-and-loss",
    id: "profit-and-loss",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Profit and Loss",
  },
  {
    description: "Assets, liabilities, and equity since the ledger went live.",
    group: "finance",
    href: "/ops/finance/balance-sheet",
    id: "balance-sheet",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Balance Sheet",
  },
  {
    description: "Bank and cash movements by source — customer receipts, supplier payments, payroll.",
    group: "finance",
    href: "/ops/finance/cash-flow-statement",
    id: "cash-flow-statement",
    navigationRoles: OPS_FINANCE_ROLES,
    phase: "Phase 13",
    roles: OPS_FINANCE_ROLES,
    status: "ready",
    title: "Cash Flow Statement",
  },
  {
    description: "Manage equipment, site requests, allocations, utilization, and related project costs.",
    group: "fleet",
    href: "/ops/equipment",
    id: "equipment",
    navigationRoles: OPS_EQUIPMENT_ROLES,
    phase: "Phase 4",
    roles: OPS_EQUIPMENT_ROLES,
    status: "ready",
    title: "Equipment",
  },
  {
    description: "Plan transport, accommodation, labour movement, dispatch calendars, and logistics costs.",
    group: "fleet",
    href: "/ops/fleet-logistics",
    id: "fleet-logistics",
    navigationRoles: OPS_FLEET_LOGISTICS_ROLES,
    phase: "Phase 4",
    roles: OPS_FLEET_LOGISTICS_ROLES,
    status: "ready",
    title: "Fleet and Logistics",
  },
  {
    description: "Report incidents and near misses, investigate causes, and close corrective actions.",
    group: "hse",
    href: "/ops/hse",
    id: "hse-incidents",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Incidents and Actions",
  },
  {
    description: "Manage Personal Protective Equipment, toolbox talks, training, inspections, risk assessments, and audit actions.",
    group: "hse",
    href: "/ops/hse-compliance",
    id: "hse-compliance",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Health, Safety and Environment Compliance",
  },
  {
    description: "Roll up the week's safety picture (incidents, near misses, Personal Protective Equipment compliance, toolbox talks) and surface it to leadership.",
    group: "hse",
    href: "/ops/hse-weekly",
    id: "hse-weekly",
    phase: "Phase 5",
    navigationRoles: OPS_HSE_ROLES,
    roles: OPS_HSE_ROLES,
    status: "ready",
    title: "Weekly Health, Safety and Environment Report",
  },
  {
    description: "Manage employee files, leave, recruitment, contracts, appraisals, and Human Resources documents.",
    group: "hr",
    href: "/ops/employees",
    id: "employees",
    phase: "Phase 5",
    navigationRoles: OPS_HR_ROLES,
    roles: OPS_HR_ROLES,
    status: "ready",
    title: "Employees and Leave",
  },
  {
    description: "Publish job openings to the website, review candidate applications, and move applicants through hiring stages.",
    group: "hr",
    href: "/ops/recruitment",
    id: "recruitment",
    phase: "Phase 5",
    navigationRoles: OPS_HR_ROLES,
    roles: OPS_HR_ROLES,
    status: "ready",
    title: "Recruitment",
  },
  {
    description: "Track Interim Payment Certificates, valuations, variations, claims, contract milestones, and commercial risk.",
    group: "commercial",
    href: "/ops/commercial",
    id: "commercial-maturity",
    navigationRoles: OPS_COMMERCIAL_ROLES,
    phase: "Phase 6",
    roles: OPS_COMMERCIAL_ROLES,
    status: "ready",
    title: "Interim Payment Certificates, Variations and Claims",
  },
  {
    description: "Monitor executive action queues, cashflow, project delay, profitability, safety, and risk.",
    group: "executive",
    href: "/ops/executive",
    id: "executive-dashboard",
    navigationRoles: OPS_EXECUTIVE_ROLES,
    phase: "Phase 7",
    roles: OPS_EXECUTIVE_ROLES,
    status: "ready",
    title: "Executive Dashboard",
  },
  {
    description: "Onboard subcontractor companies with KYC details, allocate them to project tasks at agreed rates, and track interim, retention, and final payments end-to-end.",
    group: "operations",
    href: "/ops/subcontractors",
    id: "subcontractors",
    navigationRoles: [
      ...OPS_LEADERSHIP_ROLES,
      "operations_manager",
      "projects_manager",
      "engineering_manager",
      "procurement_manager",
      "finance_manager",
      "accountant",
      "quantity_surveyor",
    ],
    phase: "Phase 6",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Subcontractors",
  },
  {
    description: "All department reports routed up for leadership review. Departments with pending reviews are surfaced first; drill into any department from here.",
    group: "executive",
    href: "/ops/department-reports",
    id: "department-reports",
    // Leadership see the all-departments roll-up here; each department's own
    // staff reach their reports through the per-department entry in their group.
    navigationRoles: OPS_LEADERSHIP_ROLES,
    phase: "Phase 7",
    roles: OPS_OPERATIONAL_ROLES,
    status: "ready",
    title: "Department Reports",
  },
  {
    description: "Operations department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "operations",
    href: "/ops/department-reports/d/operations",
    id: "dept-reports-operations",
    navigationRoles: ["operations_manager", "supervisor", "admin_receptionist"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "operations_manager", "supervisor", "admin_receptionist"],
    status: "ready",
    title: "Operations Reports",
  },
  {
    description: "Engineering department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "engineering",
    href: "/ops/department-reports/d/engineering",
    id: "dept-reports-engineering",
    navigationRoles: ["projects_manager", "engineering_manager", "engineer"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "projects_manager", "engineering_manager", "engineer"],
    status: "ready",
    title: "Engineering Reports",
  },
  {
    description: "Procurement department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "procurement",
    href: "/ops/department-reports/d/procurement",
    id: "dept-reports-procurement",
    navigationRoles: ["procurement_manager", "procurement", "procurement_assistant"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "procurement_manager", "procurement", "procurement_assistant"],
    status: "ready",
    title: "Procurement Reports",
  },
  {
    description: "Commercial department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "commercial",
    href: "/ops/department-reports/d/commercial",
    id: "dept-reports-commercial",
    navigationRoles: ["quantity_surveyor"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "quantity_surveyor"],
    status: "ready",
    title: "Commercial Reports",
  },
  {
    description: "Finance department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "finance",
    href: "/ops/department-reports/d/finance",
    id: "dept-reports-finance",
    navigationRoles: ["finance_manager", "accountant"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "finance_manager", "accountant"],
    status: "ready",
    title: "Finance Reports",
  },
  {
    description: "Health, Safety and Environment department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "hse",
    href: "/ops/department-reports/d/hse",
    id: "dept-reports-hse",
    navigationRoles: ["hse_officer", "hse_assistant_officer"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "hse_officer", "hse_assistant_officer"],
    status: "ready",
    title: "HSE Reports",
  },
  {
    description: "Human Resources department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "hr",
    href: "/ops/department-reports/d/hr",
    id: "dept-reports-hr",
    navigationRoles: ["human_resource", "hr"],
    phase: "Phase 7",
    roles: [...OPS_LEADERSHIP_ROLES, "human_resource", "hr"],
    status: "ready",
    title: "Human Resources Reports",
  },
  {
    description: "IT command centre — open help-desk tickets, SLA pressure, asset health, and equipment under repair in one place.",
    group: "it",
    href: "/ops/it",
    id: "it-overview",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-1",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "IT Overview",
  },
  {
    description: "Register every computer, laptop, printer, phone, and network device — serial numbers, assigned staff, site, warranty, and condition.",
    group: "it",
    href: "/ops/it/assets",
    id: "it-assets",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-1",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Asset Management",
  },
  {
    description: "Internal IT help desk. Any staff member can raise a support ticket; IT triages, assigns, resolves, and closes the queue.",
    group: "it",
    href: "/ops/it/helpdesk",
    id: "it-helpdesk",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-1",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Help Desk",
  },
  {
    description: "Track software subscriptions and licences — vendor, seats in use, cost, and renewal dates with expiry alerts.",
    group: "it",
    href: "/ops/it/licenses",
    id: "it-licenses",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-2",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Software & Licenses",
  },
  {
    description: "Per-employee register of which systems and accounts each person can reach. Drives clean offboarding revocation.",
    group: "it",
    href: "/ops/it/access",
    id: "it-access",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-2",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Access Register",
  },
  {
    description: "Onboarding and offboarding IT runbooks per employee — accounts, equipment, access grants, and revocation, tracked to completion.",
    group: "it",
    href: "/ops/it/checklists",
    id: "it-checklists",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-2",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Onboarding & Offboarding",
  },
  {
    description: "Publish and version IT policies — acceptable use, passwords, BYOD, cybersecurity, data retention — and track staff acknowledgement.",
    group: "it",
    href: "/ops/it/policies",
    id: "it-policies",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-2",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "IT Policies",
  },
  {
    description: "Register of shared and service accounts — owner, where the secret is stored (Bitwarden), and rotation due dates. Metadata only; never the secret itself.",
    group: "it",
    href: "/ops/it/credentials",
    id: "it-credentials",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-2",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Credential Register",
  },
  {
    description: "Inventory of routers, switches, access points, servers, firewalls, and ISP links per site, with status and maintenance notes.",
    group: "it",
    href: "/ops/it/infrastructure",
    id: "it-infrastructure",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-3",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Network & Infrastructure",
  },
  {
    description: "Log cybersecurity incidents and track backup job status so data protection and security posture stay visible.",
    group: "it",
    href: "/ops/it/security",
    id: "it-security",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-3",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Security & Backups",
  },
  {
    description: "Internal IT how-to articles so staff can self-serve common fixes and reduce repeat tickets.",
    group: "it",
    href: "/ops/it/kb",
    id: "it-kb",
    navigationRoles: OPS_IT_ROLES,
    phase: "Phase IT-3",
    roles: OPS_IT_ROLES,
    status: "ready",
    title: "Knowledge Base",
  },
  {
    description: "Information Technology department periodic reports — draft, submit for leadership review, and track acknowledgement.",
    group: "it",
    href: "/ops/department-reports/d/it",
    id: "dept-reports-it",
    navigationRoles: ["it_manager"],
    phase: "Phase IT-3",
    roles: [...OPS_LEADERSHIP_ROLES, "it_manager"],
    status: "ready",
    title: "IT Reports",
  },
  {
    description: "Raise an IT support request and track your own tickets. Available to every staff member.",
    group: "records",
    href: "/ops/it/helpdesk/mine",
    id: "it-help-request",
    navigationRoles: [...OPS_OPERATIONAL_ROLES, "engineering_intern"],
    phase: "Phase IT-1",
    roles: [...OPS_OPERATIONAL_ROLES, "engineering_intern"],
    status: "ready",
    title: "Get IT Help",
  },
  {
    description: "Read and acknowledge company IT policies, and browse IT how-to guides. Available to every staff member.",
    group: "records",
    href: "/ops/it/handbook",
    id: "it-handbook",
    navigationRoles: [...OPS_OPERATIONAL_ROLES, "engineering_intern"],
    phase: "Phase IT-3",
    roles: [...OPS_OPERATIONAL_ROLES, "engineering_intern"],
    status: "ready",
    title: "IT Policies & Guides",
  },
];
