"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { safeOpsActionErrorMessage } from "@/lib/ops/action-errors";
import { createOpsServerSessionClient, requireOpsUser } from "@/lib/ops/auth";
import { notifyOpsWorkflowEvent } from "@/lib/ops/workflow-notifications";
import {
  canArchiveInvoice,
  canCreateInvoice,
  canDeleteInvoice,
  canEditInvoice,
  canCancelInvoiceReceipt,
  canMarkInvoicePaid,
  canRecordInvoiceReceipt,
  canSendInvoice,
  canVoidInvoice,
  type OpsInvoiceMutationTarget,
} from "@/lib/ops/invoice-permissions";
import {
  postInvoiceJournalSafe,
  postInvoiceReceiptJournalSafe,
  reverseOpsJournalSafe,
} from "@/lib/ops/gl-posting";
import { todayInLusaka } from "@/lib/ops/format";
import type { OrganizationProfile } from "@/lib/ops/organization";

const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

/**
 * Creating an invoice.
 *
 * Two fields deliberately absent:
 *
 *   • **invoice_number** — always generated by `ops_next_invoice_number` from
 *     the organisation prefix. It was accepted as an optional override, which
 *     bypassed the counter entirely; two invoices sharing a number is a tax
 *     problem, not a cosmetic one. A number is now assigned, never supplied.
 *   • **boq_id** — the BOQ link was answering "where did this invoice come
 *     from" badly, and was optional so nothing depended on it. The `source` /
 *     `source_id` pair replaces it in R4
 *     (docs/pymble-ops-payables-receivables-split-2026-08.md §4b). The column
 *     stays for now; nothing writes it.
 */
const createInvoiceSchema = z.object({
  client_name: z.string().trim().min(2, "Client name is required.").max(160),
  customer_id: z
    .string()
    .trim()
    .transform((value) => (value.length > 0 ? value : null))
    .pipe(z.string().uuid().nullable()),
  issued_at: dateSchema,
  site_id: z.string().uuid("Select a Pymble site."),
  subtotal: z.coerce.number().min(0, "Subtotal cannot be negative."),
  tpin: z.string().trim().max(80).default(""),
});

const invoiceIdSchema = z.object({
  id: z.string().uuid("Select an invoice."),
});

function field(formData: FormData, name: string) {
  const value = formData.get(name);
  return typeof value === "string" ? value : "";
}

function invoiceError(message: string): never {
  redirect(`/ops/invoices?error=${encodeURIComponent(safeOpsActionErrorMessage(message))}`);
}

function roundToTwo(value: number) {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}

/**
 * Allocates the next invoice number atomically via the
 * `public.ops_next_invoice_number(prefix)` Postgres function. Numbers are
 * monotonic and gap-free per (prefix, year). Per ZRA requirements, a consumed
 * number that ends up cancelled or voided must remain on file — the function
 * does NOT recycle gaps.
 */
async function nextInvoiceNumber(prefix: string) {
  const supabase = await createOpsServerSessionClient();
  const { data, error } = await supabase.rpc("ops_next_invoice_number", {
    p_prefix: prefix,
  });

  if (error) {
    throw error;
  }

  if (typeof data !== "string" || data.length === 0) {
    throw new Error("Invoice number generator returned an empty value.");
  }

  return data;
}

/**
 * When this invoice falls due.
 *
 * Stored on the invoice rather than looked up through the customer at read
 * time: the due date is printed on the copy the client holds, so it is a fact
 * about the invoice. Reading it live would silently re-date history — and
 * restate every past ageing report — the moment somebody renegotiated terms.
 *
 * Null when there is no customer to take terms from. Ageing treats an invoice
 * with no due date as "current" rather than guessing, because an invented
 * deadline is worse than an absent one: it produces a debtor chased for a date
 * nobody agreed.
 */
async function resolveInvoiceDueDate(customerId: string | null, issuedAt: string) {
  if (!customerId) {
    return null;
  }

  const supabase = await createOpsServerSessionClient();
  const { data, error } = await supabase
    .from("customers")
    .select("payment_terms_days")
    .eq("id", customerId)
    .maybeSingle<{ payment_terms_days: number }>();

  if (error || !data) {
    return null;
  }

  const due = new Date(`${issuedAt}T00:00:00Z`);
  due.setUTCDate(due.getUTCDate() + Number(data.payment_terms_days ?? 0));
  return due.toISOString().slice(0, 10);
}

export async function createInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  if (!canCreateInvoice(profile.role)) {
    invoiceError(
      "Only the Quantity Surveyor, Finance Manager, Accountant, and leadership can create invoices.",
    );
  }

  const parsed = createInvoiceSchema.safeParse({
    client_name: field(formData, "client_name"),
    customer_id: field(formData, "customer_id"),
    issued_at: field(formData, "issued_at"),
    site_id: field(formData, "site_id"),
    subtotal: field(formData, "subtotal"),
    tpin: field(formData, "tpin"),
  });

  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Check the invoice details.");
  }

  const supabase = await createOpsServerSessionClient();
  const { data: organization, error: organizationError } = await supabase
    .from("organization_profile")
    .select("invoice_prefix, vat_rate")
    .eq("id", 1)
    .single<Pick<OrganizationProfile, "invoice_prefix" | "vat_rate">>();

  if (organizationError || !organization) {
    invoiceError(organizationError?.message ?? "Pymble organization profile was not found.");
  }

  // Always generated. See createInvoiceSchema for why there is no override.
  const invoiceNumber = await nextInvoiceNumber(organization.invoice_prefix);
  const vatAmount = roundToTwo(parsed.data.subtotal * Number(organization.vat_rate));
  const totalAmount = roundToTwo(parsed.data.subtotal + vatAmount);
  const dueDate = await resolveInvoiceDueDate(
    parsed.data.customer_id,
    parsed.data.issued_at,
  );

  const { data, error } = await supabase
    .from("invoices")
    .insert({
      client_name: parsed.data.client_name,
      created_by: profile.id,
      customer_id: parsed.data.customer_id,
      due_date: dueDate,
      invoice_number: invoiceNumber,
      issued_at: parsed.data.issued_at,
      site_id: parsed.data.site_id,
      status: "draft",
      subtotal: roundToTwo(parsed.data.subtotal),
      total_amount: totalAmount,
      tpin: parsed.data.tpin || null,
      vat_amount: vatAmount,
    })
    .select("id")
    .single<{ id: string }>();

  if (error || !data) {
    invoiceError(
      error
        ? error.code === "23505"
          ? "That invoice number already exists."
          : error.message
        : "The invoice could not be created.",
    );
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.created",
    entity_type: "invoice",
    entity_id: data.id,
    module_key: "invoices",
    source_table: "invoices",
    source_id: data.id,
    metadata: {
      due_date: dueDate,
      invoice_number: invoiceNumber,
      total_amount: totalAmount,
    },
  });

  revalidatePath("/ops");
  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?created=invoice");
}

async function fetchInvoiceMutationTarget(
  invoiceId: string,
): Promise<(OpsInvoiceMutationTarget & { id: string; invoice_number: string }) | null> {
  const supabase = await createOpsServerSessionClient();
  const { data, error } = await supabase
    .from("invoices")
    .select("id, invoice_number, status, cancelled_at, archived_at, deleted_at")
    .eq("id", invoiceId)
    .maybeSingle<OpsInvoiceMutationTarget & { id: string; invoice_number: string }>();
  if (error) {
    throw error;
  }
  return data;
}

/**
 * Sending an invoice: recognise the revenue and the receivable.
 *
 * Narrowed to "sent" only. It used to take "paid" as well and post the cash
 * journal for the whole invoice — which, now that every payment posts per
 * receipt, would book the same money twice. Settling happens through
 * writeInvoiceReceipt, and the type stops that path being re-opened by
 * accident.
 */
async function updateInvoiceStatus(id: string, status: "sent", userId: string) {
  const supabase = await createOpsServerSessionClient();
  const timestampColumn = "sent_at";
  const { data, error } = await supabase
    .from("invoices")
    .update({
      [timestampColumn]: new Date().toISOString(),
      status,
    })
    .eq("id", id)
    .select("id")
    .maybeSingle<{ id: string }>();

  if (error || !data) {
    invoiceError(error?.message ?? "Invoice status could not be updated.");
  }

  await supabase.from("audit_events").insert({
    actor_user_id: userId,
    action: `invoice.${status}`,
    entity_type: "invoice",
    entity_id: data.id,
  });

  // Revenue recognition. Best-effort + idempotent — never blocks the send.
  await postInvoiceJournalSafe(data.id, "issued", userId);

  await notifyOpsWorkflowEvent({
    actorId: userId,
    actionNeededRoles: ["finance_manager", "accountant"],
    title: `Invoice ${status}`,
    body: `An invoice was marked ${status} and the matching ledger journal was posted.`,
    actionHref: "/ops/invoices",
    moduleKey: "invoices",
    sourceTable: "invoices",
    sourceId: data.id,
    eventKey: status,
    category: "info",
  });
}

export async function sendInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = invoiceIdSchema.safeParse({ id: field(formData, "id") });

  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Select an invoice.");
  }

  const invoice = await fetchInvoiceMutationTarget(parsed.data.id);
  if (!invoice) {
    invoiceError("Invoice was not found.");
  }
  if (!canSendInvoice(profile.role, invoice)) {
    invoiceError("Only Finance and leadership can send a draft invoice.");
  }

  await updateInvoiceStatus(parsed.data.id, "sent", profile.id);

  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?updated=sent");
}

// ---------------------------------------------------------------------------
// Receipts — money actually received (R6)
// ---------------------------------------------------------------------------

const receiptSchema = z.object({
  amount: z.coerce.number().positive("Enter the amount received."),
  bank_reference: z.string().trim().max(120).default(""),
  invoice_id: z.string().uuid("Select an invoice."),
  method: z.enum(["bank_transfer", "cash", "mobile_money", "cheque", "other"]),
  notes: z.string().trim().max(400).default(""),
  received_on: dateSchema,
});

type InvoiceForReceipt = {
  id: string;
  invoice_number: string;
  status: "draft" | "sent" | "paid";
  total_amount: number | string;
  cancelled_at: string | null;
  archived_at: string | null;
  deleted_at: string | null;
};

/**
 * What is still owed on an invoice, from its receipts.
 *
 * Computed every time rather than stored (decision D6). A cached balance and a
 * list of receipts are two records of one fact, and the cached one is always
 * the one that goes stale.
 */
async function outstandingFor(invoice: InvoiceForReceipt) {
  const supabase = await createOpsServerSessionClient();
  const { data, error } = await supabase
    .from("invoice_receipts")
    .select("amount")
    .eq("invoice_id", invoice.id)
    .is("cancelled_at", null);

  if (error) {
    throw error;
  }

  const received = ((data ?? []) as Array<{ amount: number | string }>).reduce(
    (sum, row) => sum + Number(row.amount ?? 0),
    0,
  );

  return {
    outstanding: roundToTwo(Number(invoice.total_amount ?? 0) - received),
    received: roundToTwo(received),
  };
}

async function fetchInvoiceForReceipt(invoiceId: string) {
  const supabase = await createOpsServerSessionClient();
  const { data, error } = await supabase
    .from("invoices")
    .select("id, invoice_number, status, total_amount, cancelled_at, archived_at, deleted_at")
    .eq("id", invoiceId)
    .maybeSingle<InvoiceForReceipt>();

  if (error) {
    throw error;
  }

  return data;
}

/**
 * Write a receipt, post its cash, and settle the invoice if that clears it.
 *
 * The single place money-in is recorded — both `recordInvoiceReceiptAction`
 * and `markInvoicePaidAction` come through here, so there is exactly one way
 * cash reaches the ledger and one place the settled decision is made.
 */
async function writeInvoiceReceipt(input: {
  actorUserId: string;
  amount: number;
  bankReference: string;
  invoice: InvoiceForReceipt;
  method: string;
  notes: string;
  receivedOn: string;
}) {
  const supabase = await createOpsServerSessionClient();
  const { data: receipt, error } = await supabase
    .from("invoice_receipts")
    .insert({
      amount: input.amount,
      bank_reference: input.bankReference,
      invoice_id: input.invoice.id,
      method: input.method,
      notes: input.notes,
      received_on: input.receivedOn,
      recorded_by: input.actorUserId,
    })
    .select("id")
    .single<{ id: string }>();

  if (error || !receipt) {
    invoiceError(error?.message ?? "The receipt could not be recorded.");
  }

  await postInvoiceReceiptJournalSafe(receipt.id, input.actorUserId);

  // Recomputed after the insert rather than predicted from it, so a concurrent
  // receipt cannot leave the invoice open when the balance is actually clear.
  const { outstanding } = await outstandingFor(input.invoice);

  if (outstanding <= 0 && input.invoice.status !== "paid") {
    await supabase
      .from("invoices")
      .update({ paid_at: new Date().toISOString(), status: "paid" })
      .eq("id", input.invoice.id);
  }

  await supabase.from("audit_events").insert({
    actor_user_id: input.actorUserId,
    action: "invoice.receipt_recorded",
    entity_type: "invoice",
    entity_id: input.invoice.id,
    module_key: "invoices",
    source_table: "invoice_receipts",
    source_id: receipt.id,
    metadata: {
      amount: input.amount,
      bank_reference: input.bankReference,
      invoice_number: input.invoice.invoice_number,
      method: input.method,
      outstanding_after: Math.max(outstanding, 0),
      received_on: input.receivedOn,
    },
  });

  return { outstanding, receiptId: receipt.id };
}

/** Settle the whole remaining balance in one receipt. */
async function settleInvoiceByReceipt(input: {
  actorUserId: string;
  bankReference: string;
  invoiceId: string;
  method: string;
  receivedOn: string;
}) {
  const invoice = await fetchInvoiceForReceipt(input.invoiceId);

  if (!invoice) {
    invoiceError("Invoice was not found.");
  }

  const { outstanding } = await outstandingFor(invoice);

  if (outstanding <= 0) {
    invoiceError("There is nothing outstanding on this invoice.");
  }

  await writeInvoiceReceipt({
    actorUserId: input.actorUserId,
    amount: outstanding,
    bankReference: input.bankReference,
    invoice,
    method: input.method,
    notes: "Settled in full.",
    receivedOn: input.receivedOn,
  });
}

/**
 * Record a payment received against an invoice.
 *
 * Part payments are the normal case on a construction contract, which the old
 * draft/sent/paid status could not express at all. An over-payment is refused
 * rather than absorbed: it is usually a keying error, and when it is genuine it
 * needs a credit note rather than a silent surplus.
 */
export async function recordInvoiceReceiptAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = receiptSchema.safeParse({
    amount: field(formData, "amount"),
    bank_reference: field(formData, "bank_reference"),
    invoice_id: field(formData, "invoice_id"),
    method: field(formData, "method") || "bank_transfer",
    notes: field(formData, "notes"),
    received_on: field(formData, "received_on") || todayInLusaka(),
  });

  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Check the receipt details.");
  }

  const invoice = await fetchInvoiceForReceipt(parsed.data.invoice_id);

  if (!invoice) {
    invoiceError("Invoice was not found.");
  }

  if (!canRecordInvoiceReceipt(profile.role, invoice)) {
    invoiceError(
      "Only Finance and leadership can record a receipt, and only against a sent invoice.",
    );
  }

  const { outstanding } = await outstandingFor(invoice);

  if (parsed.data.amount > outstanding) {
    invoiceError(
      `That is more than the ${outstanding.toFixed(2)} still outstanding on ${invoice.invoice_number}. Record the outstanding amount, or raise a credit note for the difference.`,
    );
  }

  await writeInvoiceReceipt({
    actorUserId: profile.id,
    amount: parsed.data.amount,
    bankReference: parsed.data.bank_reference,
    invoice,
    method: parsed.data.method,
    notes: parsed.data.notes,
    receivedOn: parsed.data.received_on,
  });

  revalidatePath("/ops/invoices");
  revalidatePath("/ops/receivables");
  redirect("/ops/invoices?updated=receipt");
}

/**
 * Reverse a receipt keyed in error.
 *
 * Cancelled, never deleted: the cash has already posted a journal, and the
 * record has to show the correction rather than lose the original. Contra-ing
 * the entry keeps the immutable original intact, as everywhere else in the
 * ledger.
 */
export async function cancelInvoiceReceiptAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  if (!canCancelInvoiceReceipt(profile.role)) {
    invoiceError("Only Finance leadership can reverse a receipt.");
  }

  const receiptId = field(formData, "receipt_id");
  const reason = field(formData, "reason").trim();

  if (!/^[0-9a-f-]{36}$/i.test(receiptId)) {
    invoiceError("Select a receipt.");
  }
  if (reason.length === 0) {
    invoiceError("Give a reason — a reversed receipt without one cannot be explained later.");
  }

  const supabase = await createOpsServerSessionClient();
  const { data: receipt, error } = await supabase
    .from("invoice_receipts")
    .select("id, invoice_id, amount, cancelled_at")
    .eq("id", receiptId)
    .maybeSingle<{
      id: string;
      invoice_id: string;
      amount: number | string;
      cancelled_at: string | null;
    }>();

  if (error) {
    invoiceError(error.message);
  }
  if (!receipt) {
    invoiceError("Receipt was not found.");
  }
  if (receipt.cancelled_at) {
    invoiceError("That receipt has already been reversed.");
  }

  const { error: cancelError } = await supabase
    .from("invoice_receipts")
    .update({
      cancellation_reason: reason.slice(0, 400),
      cancelled_at: new Date().toISOString(),
      cancelled_by: profile.id,
    })
    .eq("id", receipt.id)
    .is("cancelled_at", null);

  if (cancelError) {
    invoiceError(cancelError.message);
  }

  await reverseOpsJournalSafe(
    "invoice_receipts",
    receipt.id,
    "invoice_receipt_received",
    profile.id,
  );

  // The invoice owes money again, so it is no longer settled.
  const invoice = await fetchInvoiceForReceipt(receipt.invoice_id);
  if (invoice) {
    const { outstanding } = await outstandingFor(invoice);
    if (outstanding > 0 && invoice.status === "paid") {
      await supabase
        .from("invoices")
        .update({ paid_at: null, status: "sent" })
        .eq("id", invoice.id);
    }
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.receipt_reversed",
    entity_type: "invoice",
    entity_id: receipt.invoice_id,
    module_key: "invoices",
    source_table: "invoice_receipts",
    source_id: receipt.id,
    metadata: { amount: Number(receipt.amount ?? 0), reason },
  });

  revalidatePath("/ops/invoices");
  revalidatePath("/ops/receivables");
  redirect("/ops/invoices?updated=receipt_reversed");
}

export async function markInvoicePaidAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = invoiceIdSchema.safeParse({ id: field(formData, "id") });

  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Select an invoice.");
  }

  const invoice = await fetchInvoiceMutationTarget(parsed.data.id);
  if (!invoice) {
    invoiceError("Invoice was not found.");
  }
  if (!canMarkInvoicePaid(profile.role, invoice)) {
    invoiceError("Only Finance and leadership can mark an invoice paid, and only once it has been sent.");
  }

  // Settling in full is now a RECEIPT for the whole outstanding balance, not a
  // status flip. Two reasons it has to be: the cash event is what collections,
  // DSO and the bank reconciliation are computed from, and posting the GL both
  // here and per receipt would double-count every payment. One cash path.
  await settleInvoiceByReceipt({
    actorUserId: profile.id,
    invoiceId: parsed.data.id,
    method: field(formData, "method") || "bank_transfer",
    bankReference: field(formData, "bank_reference"),
    receivedOn: field(formData, "received_on") || todayInLusaka(),
  });

  revalidatePath("/ops");
  revalidatePath("/ops/invoices");
  revalidatePath("/ops/receivables");
  redirect("/ops/invoices?updated=paid");
}

// ---------------------------------------------------------------------------
// J1: Edit / void / archive / delete actions for invoices
// ---------------------------------------------------------------------------

/**
 * Editing an invoice.
 *
 * `invoice_number` is not here on purpose. The number is allocated from a
 * gap-free per-year counter and, per ZRA, a consumed number stays on file even
 * when the invoice is voided. Letting it be edited lets someone reuse or
 * reorder a filed tax number, which the counter exists to prevent. The form
 * shows it read-only; the action does not read it at all, so a crafted POST
 * cannot change it either.
 */
const updateInvoiceSchema = invoiceIdSchema.extend({
  client_name: z.string().trim().min(2, "Client name is required.").max(160),
  issued_at: dateSchema,
  subtotal: z.coerce.number().min(0, "Subtotal cannot be negative."),
  tpin: z.string().trim().max(80).default(""),
});

const voidInvoiceSchema = invoiceIdSchema.extend({
  reason: z.string().trim().max(400).default(""),
});

export async function updateInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = updateInvoiceSchema.safeParse({
    id: field(formData, "id"),
    client_name: field(formData, "client_name"),
    issued_at: field(formData, "issued_at"),
    subtotal: field(formData, "subtotal"),
    tpin: field(formData, "tpin"),
  });
  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Check the invoice details.");
  }

  const invoice = await fetchInvoiceMutationTarget(parsed.data.id);
  if (!invoice) {
    invoiceError("Invoice was not found.");
  }
  if (!canEditInvoice(profile.role, invoice)) {
    invoiceError("Invoices can only be edited while in draft.");
  }

  const supabase = await createOpsServerSessionClient();
  const { data: organization } = await supabase
    .from("organization_profile")
    .select("vat_rate")
    .eq("id", 1)
    .maybeSingle<{ vat_rate: number | string }>();

  const vatRate = Number(organization?.vat_rate ?? 0);
  const vatAmount = roundToTwo(parsed.data.subtotal * vatRate);
  const totalAmount = roundToTwo(parsed.data.subtotal + vatAmount);

  const { error } = await supabase
    .from("invoices")
    .update({
      client_name: parsed.data.client_name,
      issued_at: parsed.data.issued_at,
      subtotal: roundToTwo(parsed.data.subtotal),
      vat_amount: vatAmount,
      total_amount: totalAmount,
      tpin: parsed.data.tpin || null,
    })
    .eq("id", parsed.data.id);
  if (error) {
    invoiceError(error.code === "23505" ? "That invoice number already exists." : error.message);
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.updated",
    entity_type: "invoice",
    entity_id: parsed.data.id,
    module_key: "invoices",
    source_table: "invoices",
    source_id: parsed.data.id,
    metadata: { total_amount: totalAmount },
  });

  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?updated=invoice");
}

export async function voidInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = voidInvoiceSchema.safeParse({
    id: field(formData, "id"),
    reason: field(formData, "reason"),
  });
  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Select an invoice.");
  }

  const invoice = await fetchInvoiceMutationTarget(parsed.data.id);
  if (!invoice) {
    invoiceError("Invoice was not found.");
  }
  if (!canVoidInvoice(profile.role, invoice)) {
    invoiceError(
      "Only Finance Manager, Managing Director, or Developer can void an invoice, and a paid invoice can't be voided (issue a credit note instead).",
    );
  }

  const supabase = await createOpsServerSessionClient();
  const nowIso = new Date().toISOString();
  const { error } = await supabase
    .from("invoices")
    .update({ cancelled_at: nowIso, cancelled_by: profile.id })
    .eq("id", parsed.data.id);
  if (error) {
    invoiceError(error.message);
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.voided",
    entity_type: "invoice",
    entity_id: parsed.data.id,
    module_key: "invoices",
    source_table: "invoices",
    source_id: parsed.data.id,
    metadata: { reason: parsed.data.reason, invoice_number: invoice.invoice_number },
  });

  // A sent invoice already posted a revenue/AR accrual — unwind it. A no-op if
  // the invoice was still draft (nothing was ever posted) or already reversed.
  await reverseOpsJournalSafe("invoices", parsed.data.id, "invoice_issued", profile.id);

  await notifyOpsWorkflowEvent({
    actorId: profile.id,
    actionNeededRoles: ["finance_manager", "accountant"],
    title: "Invoice voided",
    body: `${profile.full_name} voided an invoice. Review the receivables position.`,
    actionHref: "/ops/invoices",
    moduleKey: "invoices",
    sourceTable: "invoices",
    sourceId: parsed.data.id,
    eventKey: "voided",
    category: "info",
  });

  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?updated=voided");
}

export async function archiveInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  const parsed = invoiceIdSchema.safeParse({ id: field(formData, "id") });
  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Select an invoice.");
  }

  const invoice = await fetchInvoiceMutationTarget(parsed.data.id);
  if (!invoice) {
    invoiceError("Invoice was not found.");
  }
  if (!canArchiveInvoice(profile.role, invoice)) {
    invoiceError(
      "Invoices can only be archived once paid or voided, and only by Managing Director or Developer.",
    );
  }

  const supabase = await createOpsServerSessionClient();
  const { error } = await supabase
    .from("invoices")
    .update({ archived_at: new Date().toISOString(), archived_by: profile.id })
    .eq("id", parsed.data.id);
  if (error) {
    invoiceError(error.message);
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.archived",
    entity_type: "invoice",
    entity_id: parsed.data.id,
    module_key: "invoices",
    source_table: "invoices",
    source_id: parsed.data.id,
  });

  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?updated=archived");
}

export async function deleteInvoiceAction(formData: FormData) {
  const { profile } = await requireOpsUser();

  if (!canDeleteInvoice(profile.role)) {
    invoiceError("Only the Developer can permanently delete an invoice.");
  }

  const parsed = invoiceIdSchema.safeParse({ id: field(formData, "id") });
  if (!parsed.success) {
    invoiceError(parsed.error.issues[0]?.message ?? "Select an invoice.");
  }

  const supabase = await createOpsServerSessionClient();
  const { error } = await supabase
    .from("invoices")
    .update({ deleted_at: new Date().toISOString() })
    .eq("id", parsed.data.id);
  if (error) {
    invoiceError(error.message);
  }

  await supabase.from("audit_events").insert({
    actor_user_id: profile.id,
    action: "invoice.deleted",
    entity_type: "invoice",
    entity_id: parsed.data.id,
    module_key: "invoices",
    source_table: "invoices",
    source_id: parsed.data.id,
  });

  revalidatePath("/ops/invoices");
  redirect("/ops/invoices?updated=deleted");
}
