import { readFile } from "node:fs/promises";
import path from "node:path";
import ExcelJS from "exceljs";
import { boqLinePriceBenchmark, deriveOpsBoqLineDates, type OpsBoqDocument } from "@/lib/ops/boq";

/**
 * Material schedule Excel export (audit W1).
 *
 * Styled to match the payroll and attendance registers so the three read as one
 * family. Carries the planned figures the QS measured, the derived consumption
 * from linked material requests (A2), and the trigger dates (A4) — i.e. the
 * things that make this a schedule rather than a price list.
 */

const NAVY = "17365D";
const BLUE = "1F4E78";
const PALE_BLUE = "D9EAF7";
const PALE_GREEN = "E2F0D9";
const PALE_YELLOW = "FFF2CC";
const PALE_GREY = "F3F6F9";
const WHITE = "FFFFFF";
const CURRENCY_FORMAT = "[$ZMW] #,##0.00";
const NUMBER_FORMAT = "#,##0.00";
const HEADER_ROW = 8;

const COLUMNS = [
  ["Schedule", 26],
  ["Site", 22],
  ["Status", 14],
  ["Description", 32],
  ["Material code", 16],
  ["Unit", 10],
  ["Quantity", 12],
  ["Unit rate", 14],
  ["Planned total", 16],
  ["Classification", 20],
  ["Needed by", 13],
  ["Order by", 13],
  ["Requested qty", 14],
  ["Requested value", 16],
  ["Variance", 14],
  ["Transport", 13],
  ["Supplier", 24],
] as const;

const LAST_COLUMN = String.fromCharCode("A".charCodeAt(0) + COLUMNS.length - 1);

export type MaterialScheduleExportMeta = { generatedBy: string };

const money = (value: number) => Math.round(value * 100) / 100;

function styleCell(cell: ExcelJS.Cell, options: Partial<ExcelJS.Style>) {
  cell.style = { ...cell.style, ...options };
}

const LUSAKA_DATE = new Intl.DateTimeFormat("en-CA", {
  day: "2-digit",
  month: "2-digit",
  timeZone: "Africa/Lusaka",
  year: "numeric",
});

export function materialScheduleExportFilename(label: string) {
  const safe = label
    .trim()
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `pymble-material-schedule-${safe || "export"}.xlsx`;
}

export async function buildMaterialScheduleXlsx(
  documents: OpsBoqDocument[],
  meta: MaterialScheduleExportMeta,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Pymble Construction Operations";
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet("Material schedule", {
    pageSetup: {
      fitToHeight: 0,
      fitToPage: true,
      fitToWidth: 1,
      orientation: "landscape",
      paperSize: 9,
    },
    properties: { defaultRowHeight: 18 },
  });
  worksheet.views = [{ showGridLines: false, state: "frozen", ySplit: HEADER_ROW }];
  worksheet.columns = COLUMNS.map(([, width]) => ({ width }));
  worksheet.pageSetup.margins = {
    bottom: 0.4,
    footer: 0.15,
    header: 0.15,
    left: 0.25,
    right: 0.25,
    top: 0.4,
  };

  const logo = (await readFile(path.join(process.cwd(), "public", "logo.png"))).toString("base64");
  const logoId = workbook.addImage({ base64: logo, extension: "png" });
  worksheet.addImage(logoId, "A1:B3");

  worksheet.mergeCells(`C1:${LAST_COLUMN}1`);
  worksheet.mergeCells(`C2:${LAST_COLUMN}2`);
  worksheet.mergeCells(`C3:${LAST_COLUMN}3`);
  worksheet.getCell("C1").value = "PYMBLE CONSTRUCTION";
  worksheet.getCell("C2").value = "MATERIAL SCHEDULE";
  worksheet.getCell("C3").value =
    `${documents.length} schedule${documents.length === 1 ? "" : "s"}  |  Generated by ${meta.generatedBy} on ${LUSAKA_DATE.format(new Date())}`;
  worksheet.getRow(1).height = 26;
  worksheet.getRow(2).height = 24;
  worksheet.getRow(3).height = 22;
  styleCell(worksheet.getCell("C1"), {
    alignment: { vertical: "middle" },
    fill: { fgColor: { argb: NAVY }, pattern: "solid", type: "pattern" },
    font: { bold: true, color: { argb: WHITE }, size: 16 },
  });
  styleCell(worksheet.getCell("C2"), {
    alignment: { vertical: "middle" },
    font: { bold: true, color: { argb: NAVY }, size: 13 },
  });
  styleCell(worksheet.getCell("C3"), {
    alignment: { vertical: "middle" },
    font: { color: { argb: "404040" }, italic: true },
  });

  const allLines = documents.flatMap((document) =>
    document.items.map((item) => ({ document, item })),
  );
  const plannedTotal = money(allLines.reduce((sum, row) => sum + row.item.budgeted_total, 0));
  const requestedTotal = money(
    allLines.reduce((sum, row) => sum + row.item.actuals.requestedValue, 0),
  );
  const transportTotal = money(
    allLines.reduce((sum, row) => sum + row.item.estimated_transport_cost, 0),
  );

  const cards: Array<[string, string, string, number, string, string]> = [
    ["A5:B5", "A6:B6", "Lines", allLines.length, PALE_BLUE, NUMBER_FORMAT],
    ["C5:D5", "C6:D6", "Planned", plannedTotal, PALE_GREEN, CURRENCY_FORMAT],
    ["E5:F5", "E6:F6", "Requested", requestedTotal, PALE_YELLOW, CURRENCY_FORMAT],
    ["G5:H5", "G6:H6", "Transport", transportTotal, PALE_GREY, CURRENCY_FORMAT],
    ["I5:J5", "I6:J6", "Variance", money(plannedTotal - requestedTotal), PALE_BLUE, CURRENCY_FORMAT],
  ];

  for (const [labelRange, valueRange, label, value, fill, format] of cards) {
    worksheet.mergeCells(labelRange);
    worksheet.mergeCells(valueRange);
    const labelCell = worksheet.getCell(labelRange.split(":")[0]);
    const valueCell = worksheet.getCell(valueRange.split(":")[0]);
    labelCell.value = label;
    valueCell.value = value;
    valueCell.numFmt = format;
    styleCell(labelCell, {
      alignment: { horizontal: "center", vertical: "middle" },
      fill: { fgColor: { argb: fill }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY }, size: 9 },
    });
    styleCell(valueCell, {
      alignment: { horizontal: "center", vertical: "middle" },
      fill: { fgColor: { argb: fill }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY }, size: 12 },
    });
  }

  const headerRow = worksheet.getRow(HEADER_ROW);
  headerRow.values = COLUMNS.map(([label]) => label);
  headerRow.height = 26;
  headerRow.eachCell((cell) => {
    styleCell(cell, {
      alignment: { horizontal: "center", vertical: "middle", wrapText: true },
      fill: { fgColor: { argb: BLUE }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: WHITE }, size: 10 },
    });
  });

  allLines.forEach(({ document, item }, index) => {
    const row = worksheet.getRow(HEADER_ROW + 1 + index);
    const dates = deriveOpsBoqLineDates(item);
    const variance = money(item.budgeted_total - item.actuals.requestedValue);

    row.values = [
      `${document.title} (v${document.version})`,
      document.site?.code ? `${document.site.code} - ${document.site.name}` : "",
      document.status,
      item.description,
      item.stock_item?.item_code ?? "",
      item.unit,
      item.quantity,
      item.unit_rate,
      item.budgeted_total,
      item.category,
      dates.effectiveNeededBy ?? "",
      dates.triggerBy ?? "",
      item.actuals.requestedQuantity,
      item.actuals.requestedValue,
      variance,
      item.estimated_transport_cost,
      item.supplier
        ? `${item.supplier.supplier_code} - ${item.supplier.legal_name}`
        : (item.supplier_name_freeform ?? ""),
    ];

    for (const column of [7, 13]) row.getCell(column).numFmt = NUMBER_FORMAT;
    for (const column of [8, 9, 14, 15, 16]) row.getCell(column).numFmt = CURRENCY_FORMAT;

    if (index % 2 === 1) {
      row.eachCell((cell) => {
        styleCell(cell, {
          fill: { fgColor: { argb: PALE_GREY }, pattern: "solid", type: "pattern" },
        });
      });
    }

    // Red where the line has already been over-consumed against plan.
    if (variance < 0) {
      styleCell(row.getCell(15), { font: { bold: true, color: { argb: "9C0006" } } });
    }

    const benchmark = boqLinePriceBenchmark(item);
    if (benchmark?.isAbove) {
      styleCell(row.getCell(8), { font: { color: { argb: "9C5700" } } });
    }
  });

  const totalsRow = worksheet.getRow(HEADER_ROW + 1 + allLines.length);
  totalsRow.getCell(1).value = "TOTAL";
  totalsRow.getCell(9).value = plannedTotal;
  totalsRow.getCell(14).value = requestedTotal;
  totalsRow.getCell(15).value = money(plannedTotal - requestedTotal);
  totalsRow.getCell(16).value = transportTotal;
  for (const column of [9, 14, 15, 16]) totalsRow.getCell(column).numFmt = CURRENCY_FORMAT;
  totalsRow.eachCell((cell) => {
    styleCell(cell, {
      border: { top: { color: { argb: NAVY }, style: "medium" } },
      fill: { fgColor: { argb: PALE_BLUE }, pattern: "solid", type: "pattern" },
      font: { bold: true, color: { argb: NAVY } },
    });
  });

  worksheet.autoFilter = {
    from: { column: 1, row: HEADER_ROW },
    to: { column: COLUMNS.length, row: HEADER_ROW + allLines.length },
  };

  return Buffer.from(await workbook.xlsx.writeBuffer());
}
