-- Material schedule → budget sync: give generated lines an owner (audit B4/B3).
--
-- Problem: syncProjectBudgetFromBoq looked up its target budget line by
-- (budget_id, category) with .maybeSingle(). Nothing stopped two lines sharing
-- a category — Finance types the category as free text — so a single duplicate
-- made the lookup error, the sync throw, and the best-effort catch in
-- issueBoqAction bury it in an audit row. Every later issue for that site then
-- silently failed to generate a budget. One such duplicate already exists.
--
-- Fix: mark which lines the sync owns. `source = 'boq'` lines are generated
-- from an issued material schedule and are the sync's to create and update;
-- `source = 'manual'` lines belong to Finance and the sync must never read or
-- overwrite them. The partial unique index then guarantees the lookup can only
-- ever match one row, without constraining Finance's manual lines at all —
-- including the existing duplicate pair, which is left exactly as it is.

alter table public.project_budget_lines
  add column if not exists source text not null default 'manual'
    check (source in ('manual', 'boq'));

comment on column public.project_budget_lines.source is
  'Who owns this line: ''boq'' = generated by syncProjectBudgetFromBoq from an issued material schedule (safe to overwrite on re-issue); ''manual'' = entered by Finance (never touched by the sync).';

-- Backfill the lines the sync/ensure helpers previously created, so a future
-- sync updates them in place instead of adding a second copy alongside. These
-- are identified by the exact cost_code + description the helpers write; the
-- amounts are all zero placeholders, so this reclassifies nothing of value.
update public.project_budget_lines
set source = 'boq'
where source = 'manual'
  and (
    (cost_code = 'TRANSPORT' and description = 'Transport — planning estimate')
    or (
      cost_code = 'UNPLANNED'
      and description = 'Unplanned / contingency — requests not tied to a planned schedule line'
    )
  );

create unique index if not exists project_budget_lines_boq_category_unique
  on public.project_budget_lines (budget_id, category)
  where source = 'boq';
